import bcrypt from 'bcryptjs';

const data = {
  users: [
    {
      name: 'Anshu',
      email: 'hzb.anshu@gmail.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: true,
    },
    {
      name: 'Kumari',
      email: 'user@example.com',
      password: bcrypt.hashSync('123456'),
      isAdmin: false,
    },
  ],
  products: [
    {
      name: 'DELL Laptop',
      slug: 'DELL Laptop',
      category: 'Laptop',
      image: '/images/p5.jpg',
      price: 65000,
      countInStock: 5,
      brand: 'DELL',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Apple Laptop',
      slug: 'Apple Laptop',
      category: 'Laptop',
      image: '/images/p7.jpg',
      price: 650000,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Apple Tablet',
      slug: 'Apple Tablet',
      category: 'Tablet',
      image: '/images/p6.jpg',
      price: 80000,
      countInStock: 5,
      brand: 'Apple',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },

    {
      name: 'DELL Tablet',
      slug: 'DELL Tablet',
      category: 'Tablet',
      image: '/images/p8.jpg',
      price: 85000,
      countInStock: 5,
      brand: 'DELL',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality product',
    },

    {
      name: 'Nike Slim shirt',
      slug: 'nike-slim-shirt',
      category: 'Shirts',
      image: '/images/p1.jpg', // 679px × 829px
      price: 1200,
      countInStock: 10,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 10,
      description: 'high quality shirt',
    },
    {
      name: 'Adidas Fit Shirt',
      slug: 'adidas-fit-shirt',
      category: 'Shirts',
      image: '/images/p2.jpg',
      price: 2500,
      countInStock: 20,
      brand: 'Adidas',
      rating: 4.0,
      numReviews: 10,
      description: 'high quality product',
    },
    {
      name: 'Nike Slim Pant',
      slug: 'nike-slim-pant',
      category: 'Pants',
      image: '/images/p3.jpg',
      price: 3500,
      countInStock: 0,
      brand: 'Nike',
      rating: 4.5,
      numReviews: 14,
      description: 'high quality product',
    },
  ],
};
export default data;
